### PR TITLE
add LUT6_2 support

### PR DESCRIPTION
**Pull request by lehaifeng000**

### CODE REVIEW

**Comment by hansemro** [comment]
LUT6_2 is not a true BEL, but a macro containing both LUT6 and LUT5 BELs. The transformation from LUT6_2 to LUT6+LUT5 should be handled by NextPNR without needing to update this.

**Comment by lehaifeng000** [comment]
@hansemro 
yes, you are right.
the rtl of the LUT6_2 in vivado is LUT6+LUT5.
i need to find another way to fix it.

**Comment by hansemro** [comment]
@lehaifeng000 Please create an issue with a simple demo at https://github.com/openXC7/nextpnr-xilinx/issues. It will be helpful to know what the issue is in nextpnr-xilinx.

**Comment by hansfbaier** [comment]
> @hansemro yes, you are right. the rtl of the LUT6_2 in vivado is LUT6+LUT5. i need to find another way to fix it.

OK, I will close this PR then.
Thanks for your efforts

**Pull request closed without merging**
